[package]
name = "toy-browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
boa_engine = "0.16.0"

[workspace]
resolver = "2"

[[example]]
name = "boa-run"
path = "example/boa-run/test.rs"
